/**
 * OpenAI-compatible LLM translation client.
 *
 * Self-contained: depends only on the global `fetch` (available in the Electron
 * renderer and in modern Node). Given a batch of subtitle text lines it returns
 * their translations in the same order, preserving line breaks.
 *
 * Works with any endpoint exposing the OpenAI Chat Completions API shape, e.g.
 * SPlayer's bundled llama.cpp server, OpenAI, Azure OpenAI gateways, Groq,
 * OpenRouter, and other compatible services.
 */

export interface AITranslatorConfig {
  /** Base URL of an OpenAI-compatible API, e.g. `https://api.openai.com/v1`. */
  baseUrl: string;
  /** Bearer token. May be empty for local gateways that do not require auth. */
  apiKey: string;
  /** Chat model id, e.g. `gpt-4o-mini`. */
  model: string;
  /** Human-readable target language name, e.g. `Simplified Chinese`. */
  targetLanguage: string;
  /** Optional human-readable source language name. Auto-detected when omitted. */
  sourceLanguage?: string;
  /** Sampling temperature. Defaults to a low value for deterministic output. */
  temperature?: number;
  /** True when the Japanese source was generated by speech recognition. */
  sourceIsASR?: boolean;
}

export interface TranslateOptions {
  /** Abort the in-flight request. */
  signal?: AbortSignal;
  /** Per-request timeout in milliseconds. Defaults to 30000. */
  timeout?: number;
  /**
   * Reports an individual result as soon as it is ready. Tower translates each
   * subtitle line separately, so callers should not have to wait for every line
   * in the surrounding batch before displaying the first completed ones.
   */
  onTranslation?: (index: number, text: string) => void;
  /** Nearby source cues used only to resolve context, never translated as output. */
  contextBefore?: string[];
  contextAfter?: string[];
}

export const DEFAULT_BASE_URL = 'https://api.openai.com/v1';
export const DEFAULT_MODEL = 'gpt-4o-mini';
const DEFAULT_TIMEOUT = 30000;
const DEFAULT_TEMPERATURE = 0.2;

export class AITranslationError extends Error {
  public readonly status?: number;

  public constructor(message: string, status?: number) {
    super(message);
    this.name = 'AITranslationError';
    this.status = status;
  }
}

/** Trim trailing slashes and a trailing `/chat/completions` if the user pasted a full URL. */
function resolveEndpoint(baseUrl: string, responses = false): string {
  const url = (baseUrl || DEFAULT_BASE_URL).trim().replace(/\/+$/, '');
  if (responses && /\/responses$/.test(url)) return url;
  if (/\/chat\/completions$/.test(url)) return url;
  return `${url}/${responses ? 'responses' : 'chat/completions'}`;
}

/** Official GPT-5.x models use the Responses API. Keep other compatible
 * gateways on Chat Completions, which is still the most widely supported API. */
function usesResponsesAPI(config: AITranslatorConfig): boolean {
  const baseUrl = (config.baseUrl || DEFAULT_BASE_URL).trim();
  return /^https:\/\/(api\.)?openai\.com\/v1(?:\/|$)/i.test(baseUrl)
    && /^gpt-5(?:[.-]|$)/i.test(config.model || '');
}

export function isTowerModel(model: string): boolean {
  return /tower-plus/i.test(model || '');
}

/** Sakura GalTransl is a Japanese-to-Simplified-Chinese specialist model. */
export function isSakuraModel(model: string): boolean {
  return /sakura-galtransl|galtransl/i.test(model || '');
}

/** The Qwen2.5-based v3 line expects Sakura's native plain-text prompt. */
export function isSakuraV3Model(model: string): boolean {
  return /sakura-galtransl-v3(?:-|\.|_)/i.test(model || '');
}

function towerLanguageName(language: string): string {
  if (/^simplified chinese$/i.test(language)) return 'Chinese (Simplified)';
  if (/^traditional chinese$/i.test(language)) return 'Chinese (Traditional)';
  return language;
}

/** Use the single-source format recommended by Tower's authors. */
function buildTowerPrompt(text: string, config: AITranslatorConfig): string {
  const target = towerLanguageName(config.targetLanguage);
  const source = config.sourceLanguage
    ? towerLanguageName(config.sourceLanguage) : 'Source';
  const instruction = config.sourceLanguage
    ? `Translate the following ${source} source text to ${target}`
    : `Translate the following source text to ${target}`;
  return [
    `${instruction} as natural, concise spoken subtitles. Preserve casual tone, implied subjects,`,
    'and speaker intent; do not translate literally:',
    `${source}: ${text}`,
    `${target}: `,
  ].join('\n');
}

function buildSystemPrompt(config: AITranslatorConfig): string {
  const from = config.sourceLanguage ? `from ${config.sourceLanguage} ` : '';
  return [
    `You are a professional subtitle translator. Translate the given subtitle lines ${from}`,
    `into ${config.targetLanguage}.`,
    'Rules:',
    '- Return ONLY a JSON object of the form {"translations": ["...", "..."]}.',
    '- The "translations" array MUST have exactly the same number of items as the input, in the same order.',
    '- Use the whole batch as context to resolve pronouns, slang, tone and ambiguous wording.',
    '- Translate meaning completely, naturally and concisely, as spoken subtitles, not literally.',
    '- Preserve the speaker intent, register, humour, terminology and proper names consistently.',
    '- Preserve line breaks (\\n) inside a single line when present.',
    '- Do NOT add commentary, numbering, romanization or quotes around the text.',
    '- If a line is already in the target language or is untranslatable (e.g. a name), keep it as-is.',
  ].join(' ');
}

function buildUserPayload(texts: string[]): string {
  // Feed the lines as a JSON array so the model can align input/output unambiguously.
  return JSON.stringify({ lines: texts });
}

/** Best-effort extraction of the translations array from an arbitrary model reply. */
function parseTranslations(content: string, expectedLength: number): string[] | undefined {
  const attempts: string[] = [content];
  // The model may wrap JSON in a ```json fence or add stray prose.
  const fenced = content.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenced) attempts.unshift(fenced[1]);
  const braceMatch = content.match(/\{[\s\S]*\}/);
  if (braceMatch) attempts.push(braceMatch[0]);
  const bracketMatch = content.match(/\[[\s\S]*\]/);
  if (bracketMatch) attempts.push(bracketMatch[0]);

  for (const candidate of attempts) {
    try {
      const parsed = JSON.parse(candidate.trim());
      const arr = Array.isArray(parsed) ? parsed : parsed.translations;
      if (Array.isArray(arr) && arr.length === expectedLength) {
        return arr.map(item => (typeof item === 'string' ? item : String(item)));
      }
    } catch (e) {
      // try the next candidate
    }
  }
  return undefined;
}

async function requestCompletion(
  endpoint: string,
  body: object,
  config: AITranslatorConfig,
  options: TranslateOptions,
): Promise<string> {
  const controller = new AbortController();
  // NOTE: explicit undefined checks rather than `??` throughout this module —
  // webpack 4 cannot parse `??`/`?.`, and ts-loader passes them through untouched
  // because tsconfig targets esnext. `||` is wrong here: it would discard a
  // deliberate 0 (e.g. temperature: 0).
  const timeout = options.timeout === undefined ? DEFAULT_TIMEOUT : options.timeout;
  const timer = setTimeout(() => controller.abort(), timeout);
  const abort = () => controller.abort();
  if (options.signal) {
    if (options.signal.aborted) controller.abort();
    else options.signal.addEventListener('abort', abort, { once: true });
  }
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (config.apiKey) headers.Authorization = `Bearer ${config.apiKey}`;

  let response: Response;
  try {
    response = await fetch(endpoint, {
      method: 'POST',
      headers,
      body: JSON.stringify(body),
      signal: controller.signal,
    });
  } catch (e) {
    const err = e as Error;
    if (err.name === 'AbortError') throw new AITranslationError(`Translation request timed out after ${timeout}ms`);
    throw new AITranslationError(`Translation request failed: ${err.message}`);
  } finally {
    clearTimeout(timer);
    if (options.signal) options.signal.removeEventListener('abort', abort);
  }

  if (!response.ok) {
    const detail = await response.text().catch(() => '');
    throw new AITranslationError(
      `Translation API returned ${response.status} ${response.statusText}${detail ? `: ${detail.slice(0, 200)}` : ''}`,
      response.status,
    );
  }

  const json = await response.json().catch(() => undefined) as
    | { choices?: { message?: { content?: string }, finish_reason?: string }[], output_text?: string,
      output?: { content?: { text?: string }[] }[] }
    | undefined;
  if (json && typeof json.output_text === 'string') return json.output_text;
  if (json && Array.isArray(json.output)) {
    const output = json.output
      .reduce((all: string[], item) => all.concat((item.content || [])
        .map(part => part.text).filter((text): text is string => typeof text === 'string')), []);
    if (output.length) return output.join('');
  }
  const choices = json && json.choices;
  const first = choices && choices[0];
  if (first && first.finish_reason === 'length') {
    throw new AITranslationError('Translation API response was truncated at the token limit');
  }
  const message = first && first.message;
  const content = message && message.content;
  if (typeof content !== 'string') throw new AITranslationError('Translation API returned an unexpected response shape');
  return content;
}

async function translateTowerLines(
  texts: string[],
  config: AITranslatorConfig,
  options: TranslateOptions,
): Promise<string[]> {
  const endpoint = resolveEndpoint(config.baseUrl);
  const translated = new Array<string>(texts.length);
  let nextIndex = 0;
  const worker = async () => {
    while (nextIndex < texts.length) {
      const index = nextIndex;
      nextIndex += 1;
      const content = await requestCompletion(endpoint, {
        model: config.model,
        temperature: 0,
        max_tokens: 512,
        messages: [{ role: 'user', content: buildTowerPrompt(texts[index], config) }],
      }, config, options);
      const text = content.trim();
      if (!text) throw new AITranslationError('Tower+ returned an empty translation');
      translated[index] = text;
      if (options.onTranslation) options.onTranslation(index, text);
    }
  };
  // Two in-flight lines keep local inference busy without flooding its queue.
  const workers = new Array(Math.min(2, texts.length)).fill(undefined).map(() => worker());
  await Promise.all(workers);
  return translated;
}

function buildSakuraBaseSystemPrompt(config: AITranslatorConfig): string {
  return [
    '你是一个视觉小说翻译模型，可以通顺地使用给定的术语表以指定的风格将日文翻译成简体中文，',
    '并联系上下文正确使用人称代词，注意不要混淆使役态和被动态的主语和宾语，',
    '不要擅自添加原文中没有的特殊符号，也不要擅自增加或减少换行。',
    config.sourceIsASR
      ? '输入来自日语语音识别，可能有同音字、近音词、漏标点或错误断句；请结合前后文理解最合理的原意，避免直译明显不通的识别结果，也不要编造剧情。'
      : '',
  ].join('');
}

/** The Qwen3-based v4 model reliably supports llama.cpp's JSON schema grammar. */
function buildSakuraStructuredSystemPrompt(config: AITranslatorConfig): string {
  return [
    buildSakuraBaseSystemPrompt(config),
    '利用整批字幕理解上下文并逐条翻译。translations数组的数量和顺序必须与输入完全一致，',
    '只输出JSON对象，不要重复原文、历史译文、编号、Markdown或解释。',
  ].join('');
}

function sakuraContextPayload(texts: string[], options: TranslateOptions) {
  return {
    context_before: options.contextBefore || [],
    lines: texts,
    context_after: options.contextAfter || [],
  };
}

function sakuraResponseFormat(expectedLength: number) {
  return {
    type: 'json_schema',
    json_schema: {
      name: 'subtitle_translations',
      strict: true,
      schema: {
        type: 'object',
        additionalProperties: false,
        properties: {
          translations: {
            type: 'array',
            minItems: expectedLength,
            maxItems: expectedLength,
            items: { type: 'string', minLength: 1 },
          },
        },
        required: ['translations'],
      },
    },
  };
}

/**
 * Translate Sakura cues as one context-aware batch. llama.cpp's JSON schema
 * grammar guarantees that every input cue has exactly one output slot; this
 * prevents prior translations or prose from shifting text onto another cue.
 */
async function translateStructuredSakuraLines(
  texts: string[],
  config: AITranslatorConfig,
  options: TranslateOptions,
): Promise<string[]> {
  const endpoint = resolveEndpoint(config.baseUrl);
  const content = await requestCompletion(endpoint, {
    model: config.model,
    temperature: 0.1,
    top_p: 0.3,
    max_tokens: 2048,
    response_format: sakuraResponseFormat(texts.length),
    messages: [
      { role: 'system', content: buildSakuraStructuredSystemPrompt(config) },
      { role: 'user', content: JSON.stringify(sakuraContextPayload(texts, options)) },
    ],
  }, config, options);
  const translations = parseTranslations(content, texts.length);
  const ready = translations && translations.map(text => text.trim());
  if (!ready || ready.some(text => !text)) {
    throw new AITranslationError(
      `Sakura GalTransl returned ${texts.length} input cue(s) without a complete aligned translation array`,
    );
  }
  if (options.onTranslation) {
    ready.forEach((text, index) => options.onTranslation!(index, text));
  }
  return ready;
}

const SAKURA_LINE_BREAK = '⟪SPLAYER_BR⟫';

function encodeSakuraCue(text: string): string {
  return text.replace(/\r?\n/g, SAKURA_LINE_BREAK).trim();
}

function buildSakuraV3Prompt(texts: string[], options: TranslateOptions): string {
  const sections: string[] = [];
  const before = options.contextBefore || [];
  const after = options.contextAfter || [];
  if (before.length) {
    sections.push(`前文（日文，仅供理解，不要输出）：\n${before.map(encodeSakuraCue).join('\n')}`);
  }
  if (after.length) {
    sections.push(`后文（日文，仅供理解，不要输出）：\n${after.map(encodeSakuraCue).join('\n')}`);
  }
  sections.push('参考以下术语表（可以为空）：');
  sections.push([
    '逐行翻译下面标记后的日文。每个 [SPLAYER_n] 标记必须原样保留并恰好输出一次；',
    '只输出标记和对应简体中文，不合并、不拆分、不解释：',
    texts.map((text, index) => `[SPLAYER_${index}] ${encodeSakuraCue(text)}`).join('\n'),
  ].join('\n'));
  return sections.join('\n\n');
}

function parseMarkedTranslations(content: string, expectedLength: number): string[] | undefined {
  const found = new Array<string | undefined>(expectedLength).fill(undefined);
  const pattern = /^\s*\[SPLAYER_(\d+)\]\s*(.*?)\s*$/gm;
  let match = pattern.exec(content);
  while (match) {
    const index = parseInt(match[1], 10);
    if (index < expectedLength && found[index] === undefined && match[2]) {
      found[index] = match[2].replace(new RegExp(SAKURA_LINE_BREAK, 'g'), '\n').trim();
    }
    match = pattern.exec(content);
  }
  return found.every(value => typeof value === 'string' && !!value)
    ? found as string[] : undefined;
}

function withoutTranslationCallback(options: TranslateOptions): TranslateOptions {
  return { ...options, onTranslation: undefined };
}

async function translateSakuraV3Aligned(
  texts: string[],
  config: AITranslatorConfig,
  options: TranslateOptions,
): Promise<string[]> {
  const endpoint = resolveEndpoint(config.baseUrl);
  const content = await requestCompletion(endpoint, {
    model: config.model,
    temperature: config.temperature === undefined ? 0.1 : config.temperature,
    top_p: 0.3,
    max_tokens: 1024,
    messages: [
      { role: 'system', content: buildSakuraBaseSystemPrompt(config) },
      { role: 'user', content: buildSakuraV3Prompt(texts, options) },
    ],
  }, config, withoutTranslationCallback(options));
  const translated = parseMarkedTranslations(content, texts.length);
  if (translated) return translated;
  if (texts.length === 1) {
    const fallback = content.trim().replace(/^\[SPLAYER_0\]\s*/, '').trim();
    if (fallback && !/\[SPLAYER_\d+\]/.test(fallback)) return [fallback];
    throw new AITranslationError('Sakura GalTransl v3 returned an unaligned single-cue translation');
  }
  const middle = Math.ceil(texts.length / 2);
  const left = texts.slice(0, middle);
  const right = texts.slice(middle);
  const baseBefore = options.contextBefore || [];
  const baseAfter = options.contextAfter || [];
  const leftResult = await translateSakuraV3Aligned(left, config, {
    ...options,
    contextBefore: baseBefore,
    contextAfter: right.concat(baseAfter).slice(0, 4),
  });
  const rightResult = await translateSakuraV3Aligned(right, config, {
    ...options,
    contextBefore: baseBefore.concat(left).slice(-4),
    contextAfter: baseAfter,
  });
  return leftResult.concat(rightResult);
}

/**
 * Sakura v3.8 was trained for plain multi-line translation and can loop until
 * max_tokens when forced through a JSON grammar. Use its native prompt, then
 * fall back to independent cues if it ever changes the line count.
 */
async function translateSakuraV3Lines(
  texts: string[],
  config: AITranslatorConfig,
  options: TranslateOptions,
): Promise<string[]> {
  const translated = await translateSakuraV3Aligned(texts, config, options);
  if (options.onTranslation) {
    translated.forEach((text, index) => options.onTranslation!(index, text));
  }
  return translated;
}

/**
 * Translate an array of subtitle text lines, resolving with an array of the same
 * length and order.
 *
 * Throws `AITranslationError` when the reply cannot be aligned to the input, so
 * the caller can retry it like any other failure. It deliberately does NOT fall
 * back to returning the source lines: to a caller that is indistinguishable from
 * a successful translation, so the untranslated text gets cached and shown
 * forever. Callers keep subtitles readable by displaying the source text while a
 * translation is missing (see `RealtimeSubtitleTranslator`).
 */
export async function translateLines(
  texts: string[],
  config: AITranslatorConfig,
  options: TranslateOptions = {},
): Promise<string[]> {
  if (!texts.length) return [];
  if (isTowerModel(config.model)) return translateTowerLines(texts, config, options);
  if (isSakuraV3Model(config.model)) return translateSakuraV3Lines(texts, config, options);
  if (isSakuraModel(config.model)) return translateStructuredSakuraLines(texts, config, options);
  const responses = usesResponsesAPI(config);
  const endpoint = resolveEndpoint(config.baseUrl, responses);
  const body = responses
    ? {
      model: config.model || DEFAULT_MODEL,
      input: [
        { role: 'system', content: buildSystemPrompt(config) },
        { role: 'user', content: buildUserPayload(texts) },
      ],
    }
    : {
      model: config.model || DEFAULT_MODEL,
      temperature: config.temperature === undefined ? DEFAULT_TEMPERATURE : config.temperature,
      messages: [
        { role: 'system', content: buildSystemPrompt(config) },
        { role: 'user', content: buildUserPayload(texts) },
      ],
    };
  const content = await requestCompletion(endpoint, body, config, options);
  const translations = parseTranslations(content, texts.length);
  if (!translations) {
    throw new AITranslationError(
      `Translation API returned ${texts.length} line(s) worth of input but a reply that could not be aligned to it`,
    );
  }
  return translations;
}
