import groovy.json.JsonSlurper

plugins {
    id "com.android.application"
}

def desktopPackage = new JsonSlurper().parse(rootProject.file("../package.json"))

android {
    namespace "org.splayer.tv"
    compileSdk 35

    defaultConfig {
        applicationId "org.splayer.tv"
        minSdk 23
        targetSdk 35
        versionCode 41180
        versionName desktopPackage.version

        testInstrumentationRunner "android.test.InstrumentationTestRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"),
                    "proguard-rules.pro"
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += [
                    "META-INF/DEPENDENCIES",
                    "META-INF/LICENSE",
                    "META-INF/LICENSE.txt",
                    "META-INF/NOTICE",
                    "META-INF/NOTICE.txt"
            ]
        }
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:2.1.4"
    implementation "com.google.code.gson:gson:2.11.0"
    implementation "com.squareup.okhttp3:okhttp:4.12.0"
    implementation "eu.agno3.jcifs:jcifs-ng:2.1.10"
    implementation "org.slf4j:slf4j-android:1.7.36"

    testImplementation "junit:junit:4.13.2"
}
