
export const FILE_NON_EXIST = 'FILE_NON_EXIST';
export const PLAYLIST_NON_EXIST = 'PLAYLIST_NON_EXIST';
export const FILE_NON_EXIST_IN_PLAYLIST = 'FILE_NON_EXIST_IN_PLAYLIST';
export const EMPTY_FOLDER = 'EMPTY_FOLDER';
export const OPEN_FAILED = 'OPEN_FAILED';
export const ONLINE_LOADING = 'ONLINE_LOADING';
export const SUBTITLE_OFFLINE = 'SUBTITLE_OFFLINE';
export const NOT_SUPPORTED_SUBTITLE = 'NOT_SUPPORTED_SUBTITLE';
export const REQUEST_TIMEOUT = 'REQUEST_TIMEOUT';
export const SUBTITLE_UPLOAD = 'SUBTITLE_UPLOAD';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILED = 'UPLOAD_FAILED';
export const CANNOT_UPLOAD = 'CANNOT_UPLOAD';
export const CANNOT_EXPORT = 'CANNOT_EXPORT';
export const ADD_NO_VIDEO = 'ADD_NO_VIDEO';
export const LOCAL_SUBTITLE_REMOVED = 'LOCAL_SUBTITLE_REMOVED';
export const AI_TRANSLATE_NO_SOURCE = 'AI_TRANSLATE_NO_SOURCE';
export const AI_TRANSLATE_NO_PROVIDER = 'AI_TRANSLATE_NO_PROVIDER';
export const AI_TRANSLATE_NO_WHISPER = 'AI_TRANSLATE_NO_WHISPER';
export const AI_TRANSCRIBE_FAILED = 'AI_TRANSCRIBE_FAILED';
export const AI_TRANSCRIBE_NO_SPEECH = 'AI_TRANSCRIBE_NO_SPEECH';
export const CAST_NO_DEVICE = 'CAST_NO_DEVICE';
export const CAST_NOT_LOCAL = 'CAST_NOT_LOCAL';
export const CAST_UNSUPPORTED = 'CAST_UNSUPPORTED';
export const CAST_FAILED = 'CAST_FAILED';
export const SNAPSHOT_FAILED = 'SNAPSHOT_FAILED';
export const SNAPSHOT_SUCCESS = 'SNAPSHOT_SUCCESS';
export const THUMBNAIL_GENERATE = 'THUMBNAIL_GENERATE';
export const THUMBNAIL_GENERATE_SUCCESS = 'THUMBNAIL_GENERATE_SUCCESS';
export const THUMBNAIL_GENERATE_FAILED = 'THUMBNAIL_GENERATE_FAILED';
export const LOAD_SUBVIDEO_FAILED = 'LOAD_SUBVIDEO_FAILED';
export const BUG_UPLOADING = 'BUG_UPLOADING ';
export const BUG_UPLOAD_SUCCESS = 'BUG_UPLOAD_SUCCESS ';
export const BUG_UPLOAD_FAILED = 'BUG_UPLOAD_FAILED ';
export const ENOSPC = 'ENOSPC';
export const EACCES = 'EACCES';
export const EPERM = 'EPERM';
export const ENOENT = 'ENOENT';
/** 检查更新气泡 */
export const CHECK_FOR_UPDATES_OFFLINE = 'CHECK_FOR_UPDATES_OFFLINE';
/** 字幕编辑通用气泡 */
export const SUBTITLE_EDITOR_SAVED = 'SUBTITLE_EDITOR_SAVED';
export const SUBTITLE_EDITOR_REFERENCE_LOADING = 'SUBTITLE_EDITOR_REFERENCE_LOADING';
export const SUBTITLE_EDITOR_REFERENCE_LOAD_FAIL = 'SUBTITLE_EDITOR_REFERENCE_LOAD_FAIL';
/** APPX禁止支付相关 */
export const APPX_EXPORT_NOT_WORK = 'APPX_EXPORT_NOT_WORK';
/** LosslessStreaming */
export const LOSSLESS_STREAMING_START = 'LOSSLESS_STREAMING_START';
export const LOSSLESS_STREAMING_STOP = 'LOSSLESS_STREAMING_STOP';
